name: fhir_questionnaire
description: "A library to render FHIR Questionnaires and generate a QuestionnaireResponse"
version: 0.0.1
repository: https://github.com/luis901101/fhir_questionnaire
issue_tracker: https://github.com/luis901101/fhir_questionnaire/issues
topics:
  - fhir
  - questionnaire
  - hl7
  - r4

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  shimmer: ^3.0.0
  fhir: ^0.12.0
  intl: ^0.19.0
  duration: ^3.0.13
  html: ^0.15.4
  intl_phone_field: ^3.2.0
  adeptviews: ^12.0.0+1
  adeptutils: ^10.0.0+1

dependency_overrides:
  intl: ^0.19.0 # To fix some dependencies conflicts because of using distinct versions, which should not be a problem because the major version is still the same.


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
